[phases.setup]
nixPkgs = ["python311"]
cmds = [
  "python3 -m venv /app/.venv",
  "/app/.venv/bin/pip install --upgrade pip"
]

[phases.install]
cmds = ["/app/.venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/app/.venv/bin/python bot_simples.py"
